# Generated by Django 5.1.4 on 2024-12-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b13", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeeksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("last_modified", models.DateTimeField(auto_now_add=True)),
                ("img", models.ImageField(upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="vechile",
            name="customer",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Vechile",
        ),
    ]
