# Generated by Django 5.1.4 on 2024-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b13", "0002_geeksmodel_remove_vechile_customer_delete_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="GeeksModel",
        ),
    ]
